var N = null;var sourcesIndex = {};
sourcesIndex["tydi_db"] = {"name":"","files":["lib.rs"]};
sourcesIndex["tydi_designs"] = {"name":"","files":["lib.rs"]};
sourcesIndex["tydi_dot"] = {"name":"","files":["lib.rs","node.rs","style.rs"]};
sourcesIndex["tydi_hcl"] = {"name":"","files":["lib.rs"]};
sourcesIndex["tydi_hir"] = {"name":"","files":["component.rs","identifier.rs","lib.rs","net.rs","type.rs"]};
sourcesIndex["tydi_intern"] = {"name":"","files":["lib.rs"]};
sourcesIndex["tydi_lexer"] = {"name":"","files":["lib.rs"]};
sourcesIndex["tydi_manifest"] = {"name":"","files":["lib.rs"]};
sourcesIndex["tydi_syntax"] = {"name":"","files":["lib.rs"]};
createSourceSidebar();
